version: '3'

services:

  vc-db:
    image: microsoft/mssql-server-windows-express
    ports:
      - "1433:1433"
    environment: 
      - ACCEPT_EULA=Y
      - sa_password=v!rto_Labs!
    networks:
      - virto

  vc-platform-web:
    image: virtocommerce/platform:latest
    ports:
      - "8090:80"
    environment:
      - VIRTO_CONN_STR_VIRTOCOMMERCE=Data Source=vc-db;Initial Catalog=VirtoCommerce2;Persist Security Info=True;User ID=sa;Password=v!rto_Labs!;MultipleActiveResultSets=True;Connect Timeout=30;
      - VIRTO_CONN_STR_AssetsConnectionString=provider=LocalStorage;rootPath=~/App_Data/Assets;publicUrl=http://192.168.1.107:8090/assets
    depends_on:
      - vc-db
    networks:
      - virto

  vc-storefront-web:
    image: virtocommerce/storefront:latest
    ports:
      - "8080:80"
    environment:
      - VIRTO_CONN_STR_VirtoCommerceBaseUrl=http://vc-platform-web
    depends_on:
      - vc-platform-web
    networks:
      - virto

networks:
  virto:
    external:
      name: nat
