version: '3.6'

services:

  vc-db:
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    ports:
      - "${DOCKER_SQL_PORT:-1433}:1433"
    expose:  
      - 1433  
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=v!rto_Labs!
    networks:
      - virto

  vc-platform-web:
    image:  ${DOCKER_REGISTRY-}vc-platform-web-3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${DOCKER_PLATFORM_PORT:-8091}:443"
    environment:
      - ASPNETCORE_URLS=https://+
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DOCKER_PLATFORM_CERT_PASS}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/${DOCKER_PLATFORM_CERT_NAME}
      - ASPNETCORE_HTTPS_PORT=${DOCKER_PLATFORM_PORT:-8091}
      - ConnectionStrings:VirtoCommerce=Data Source=vc-db;Initial Catalog=VirtoCommerce3docker;Persist Security Info=True;User ID=sa;Password=v!rto_Labs!;MultipleActiveResultSets=False;
      - Assets:FileSystem:PublicUrl=https://localhost:${DOCKER_PLATFORM_PORT:-8091}/assets/
      - Content:FileSystem:PublicUrl=https://localhost:${DOCKER_PLATFORM_PORT:-8091}/cms-content/
    depends_on:
      - vc-db
    volumes:
      - ./https:/https/
    networks:
      - virto


networks:
  virto:
